---

- name: Re-create websites container
  docker_container:
    name: website
    image: docker.io/playtechnique/website:latest
    state: started
    recreate: yes
    pull: true
    exposed_ports:
      - 8080
    published_ports:
      - "443:8080"
    volumes:
      - /home/playtechnique/ssl:/etc/ssl/playtechnique:ro
    command:
      - "-c"
      - "/etc/ssl/playtechnique/playtechnique_io.crt"
      - "-p"
      - "/etc/ssl/playtechnique/playtechnique_io.key"
      - "-d"
      #upon detecting the space in the argument to -d, ansible arranges to surround the arg with quotes on our behalf.
      - "Improving, playfully"
      - "-t"
      - "PlayTechnique"
      - "/website"
      - "0.0.0.0:8080"
      - "https://playtechnique.io"
    restart_policy: always
