apiVersion: apps/v1
kind: Deployment
metadata:
  name: playtechnique-website
spec:
  template:
    spec:
      containers:
        - name: website
          image: "docker.io/playtechnique/website:25"
          command: ["/andrew", "/website", "0.0.0.0:8080", "https://playtechnique.io"]
