---

- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    cache_valid_time: 3600
  ignore_errors: true
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    cache_valid_time: 3600
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    cache_valid_time: 3600
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
- name: Ensure user "playtechnique" is in the "docker" group
  ansible.builtin.user:
    name: playtechnique
    groups: docker
    append: yes
- name: install pip to install the docker python module
  apt:
    name: python3-pip
    state: latest
    cache_valid_time: 3600
- name: Install docker python extension to manage the container
  ansible.builtin.pip:
    name: docker-py