name: Release to Production

on:
  push:
    paths: 
      - 'website/k8s-manifests/overlays/**'
  workflow_call:
    inputs:
      docker-image:
        description: 'Docker image plus tag to udpate to'
        required: true
        type: string
jobs:
  update-container-version-patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: validate input
        run: |
          if [ -z "${{ inputs.docker-image }}" ]; then
            echo "Input was ${{ inputs.docker-image }}. Bailing".
            exit 1
          fi

      - name: edit file
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ inputs.docker-image }}"' -i website-deployment/k8s-manifests/overlays/production/deployment-container-version-patch.yaml
      
      - name: commit back to github
        run: |
          git config --global user.name 'Playtechnique github bot'
          git config --global user.email 'github-bot@playtechnique.io'
          git commit -am "Updates production deployment with ${{ inputs.docker-image }} "
          git push